server:
  port: 8085

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

datasources:
  url:
    primary: jdbc:postgresql://localhost:5432/write
    replica: jdbc:postgresql://localhost:5432/read
  username: postgres
  password: password